openapi: 3.0.1
info:
  title: Twilio - Accounts
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: AccountsV1AuthTokenPromotion
  - name: AccountsV1Aws
  - name: AccountsV1PublicKey
  - name: AccountsV1Safelist
  - name: AccountsV1SecondaryAuthToken
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: >-
      PLEASE NOTE that this is a Beta product that is subject to change. Use it
      with caution.
paths:
  /v1/AuthTokens/Promote:
    description: Auth Token promotion
    post:
      description: >-
        Promote the secondary Auth Token to primary. After promoting the new
        token, all requests to Twilio using your old primary Auth Token will
        result in an error.
      tags:
        - Authentication
        - Promote
        - Tokens
      summary: Promote Authentication Tokens
  /v1/Credentials:
    description: 'TODO: Resource-level docs'
  /v1/Credentials/AWS:
    description: User provided AWS keys
    get:
      description: >-
        This API retrieves a collection of AWS Credentials associated with the
        account that made the request.
      tags:
        - Authentication
        - Credentials
        - Promote
        - Tokens
      summary: Retrieve Collection of AWS Credentials
    post:
      description: Generate new AWS credentials for accessing this API.
      tags:
        - Authentication
        - Credentials
        - Promote
        - Tokens
      summary: Create AWS Credential
  /v1/Credentials/AWS/{Sid}:
    description: User provided AWS keys
    get:
      description: Fetch the AWS credentials specified by the provided Credential Sid
      tags:
        - AWS
        - Credentials
        - Retrieve
      summary: 'Retrieve AWS Credentials '
    post:
      description: Modify the properties of a given Account
      tags:
        - AWS
        - Accounts
        - Credentials
        - Modify
      summary: Modify AWS Account
    delete:
      description: Delete a Credential from your account
      tags:
        - AWS
        - Credentials
      summary: Delete AWS Credential
  /v1/Credentials/PublicKeys:
    description: User provided public keys
    get:
      description: >-
        Retrieves a collection of Public Key Credentials belonging to the
        account used to make the request
      tags:
        - Credentials
        - Keys
        - Public
        - Retrieve
      summary: Retrieve Public Key Credentials
    post:
      description: Generate a fresh Public Key Credential by utilizing this API.
      tags:
        - Credentials
        - Keys
        - Public
      summary: Create Public Key Credential
  /v1/Credentials/PublicKeys/{Sid}:
    description: User provided public keys
    get:
      description: Fetch the public key specified by the provided Credential Sid
      tags:
        - Credentials
        - Keys
        - Public
        - Retrieve
      summary: Retrieve Public Key Credentials
    post:
      description: Modify the properties of a given Account
      tags:
        - Credentials
        - Keys
        - Modify
        - Public
      summary: Modify Public Key Credential
    delete:
      description: Delete a Credential from your account
      tags:
        - Credentials
        - Keys
        - Public
      summary: Delete Public Key Credential
  /v1/SafeList/Numbers:
    description: 'TODO: Resource-level docs'
    post:
      description: Add a new phone number to SafeList.
      tags:
        - Lists
        - Numbers
        - Phone
        - Safe
      summary: Add Safe List Phone Number
    get:
      description: Check if a phone number exists in SafeList.
      tags:
        - Checks
        - Numbers
        - Phone
        - Safe
      summary: Check If Phone Number  on Safe List
    delete:
      description: Remove a phone number from SafeList.
      tags:
        - From
        - Numbers
        - Phone
        - Removes
        - Safe
      summary: Remove Phone Number from Safe List
  /v1/AuthTokens/Secondary:
    description: Secondary Auth Token
    post:
      description: Create a new secondary Auth Token
      tags:
        - Authentication
        - Secondary
        - Tokens
      summary: Create Secondary Authentication Token
    delete:
      description: Delete the secondary Auth Token from your account
      tags:
        - Authentication
        - Secondary
        - Tokens
      summary: Delete Secondary Authentication Token
