info:
  title: Assistants
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /understand/Assistants/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Retrieve
        - Understand
      summary: Retrieve Assistant
    post:
      description: ''
      tags:
        - Assistants
        - Understand
      summary: Create Assistant
    delete:
      description: ''
      tags:
        - Assistants
        - Assistants
        - Understand
      summary: Delete Assistant
  /understand/Assistants/{AssistantSid}/FallbackActions:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Actions
        - Assistants
        - Fallback
        - Retrieve
        - Understand
      summary: Retrieve Assistant Fallback Actions
    post:
      description: ''
      tags:
        - Actions
        - Assistants
        - Fallback
        - Understand
      summary: Create Assistant Fallback Actions
  /understand/Assistants/{AssistantSid}/InitiationActions:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Actions
        - Assistants
        - Initiation
        - Retrieve
        - Understand
      summary: Retrieve Assistant Initiation Actions
    post:
      description: ''
      tags:
        - Actions
        - Assistants
        - Initiation
        - Understand
      summary: Create Assistant Initiation Actions
  /understand/Assistants/{AssistantSid}/Dialogues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Dialogues
        - Retrieve
        - Understand
      summary: Retrieve Assistant Dialogues
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Fields
        - Retrieve
        - Tasks
        - Understand
      summary: Retrieve Assistant Task Fields
    delete:
      description: ''
      tags:
        - Assistants
        - Fields
        - Tasks
        - Understand
      summary: Delete Assistant Task Fields
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Fields
        - Retrieve
        - Tasks
        - Understand
      summary: Retrieve Assistant Task Fields
    post:
      description: ''
      tags:
        - Assistants
        - Fields
        - Tasks
        - Understand
      summary: Create Assistant Task Fields
  /understand/Assistants/{AssistantSid}/FieldTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
      summary: Retrieve Assistant Field Types
    post:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
      summary: Create Assistant Field Type
    delete:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
      summary: Delete Assistant Field Type
  /understand/Assistants/{AssistantSid}/FieldTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
      summary: Retrieve Assistant Field Types
    post:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
      summary: Create Assistant Field Types
  /understand/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
        - Value
        - Values
      summary: Retrieve Assistant Field Type Field Value
    delete:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
        - Value
        - Values
      summary: Delete Assistant Field Type Field Value
  /understand/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
        - Values
      summary: Retrieve Assistant Field Type Field Values
    post:
      description: ''
      tags:
        - Assistants
        - Fields
        - Types
        - Understand
        - Values
      summary: Create Assistant Field Type Field Values
  /understand/Assistants/{AssistantSid}/ModelBuilds/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Build
        - Builds
        - Models
        - Understand
      summary: Retrieve Assistant Model Build
    post:
      description: ''
      tags:
        - Assistants
        - Build
        - Builds
        - Models
        - Understand
      summary: Update Assistant Model Build
    delete:
      description: ''
      tags:
        - Assistants
        - Build
        - Builds
        - Models
        - Understand
      summary: Delete Assistant Model Build
  /understand/Assistants/{AssistantSid}/ModelBuilds:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Builds
        - Models
        - Understand
      summary: Retrieve Assistant Model Builds
    post:
      description: ''
      tags:
        - Assistants
        - Build
        - Builds
        - Models
        - Understand
      summary: Create Assistant Model Build
  /understand/Assistants/{AssistantSid}/Queries/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Queries
        - Understand
      summary: Retrieve Assistant Query
    post:
      description: ''
      tags:
        - Assistants
        - Queries
        - Understand
      summary: Create Assistant Query
    delete:
      description: ''
      tags:
        - Assistants
        - Queries
        - Understand
      summary: Delete Assistant Query
  /understand/Assistants/{AssistantSid}/Queries:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Queries
        - Understand
      summary: Retrieve Assistant Queries
    post:
      description: ''
      tags:
        - Assistants
        - Queries
        - Understand
      summary: Create Assistant Query
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Samples
        - Tasks
        - Understand
      summary: Retrieve Assistant Task Sample
    post:
      description: ''
      tags:
        - Assistants
        - Samples
        - Tasks
        - Understand
      summary: Update Assistant Task Sample
    delete:
      description: ''
      tags:
        - Assistants
        - Samples
        - Tasks
        - Understand
      summary: Delete Assistant Task Sample
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Samples
        - Tasks
        - Understand
      summary: Retrieve Assistant Task Samples
    post:
      description: ''
      tags:
        - Assistants
        - Samples
        - Tasks
        - Understand
      summary: Create Assistant Task Sample
  /understand/Assistants/{AssistantSid}/StyleSheet:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns Style sheet JSON object for this Assistant
      tags:
        - Assistants
        - Sheet
        - Sheets
        - Styles
        - Understand
      summary: Retrieve Assistant Style Sheets
    post:
      description: >-
        Updates the style sheet for an assistant identified by {AssistantSid} or
        {AssistantUniqueName}.
      tags:
        - Assistants
        - Sheet
        - Styles
        - Understand
      summary: Create Assistant Style Sheet
  /understand/Assistants/{AssistantSid}/Tasks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Tasks
        - Understand
      summary: Retrieve Assistant Task
    post:
      description: ''
      tags:
        - Assistants
        - Tasks
        - Understand
      summary: Update Assistant Task
    delete:
      description: ''
      tags:
        - Assistants
        - Tasks
        - Understand
      summary: Delete Assistant Task
  /understand/Assistants/{AssistantSid}/Tasks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Tasks
        - Understand
      summary: Retrieve Assistant Tasks
    post:
      description: ''
      tags:
        - Assistants
        - Tasks
        - Understand
      summary: Create Assistant Task
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Actions:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns JSON actions for this Task.
      tags:
        - Actions
        - Assistants
        - Tasks
        - Understand
      summary: Retrieve Assistant Task Actions
    post:
      description: >-
        Updates the actions of an Task identified by {TaskSid} or
        {TaskUniqueName}.
      tags:
        - Actions
        - Assistants
        - Tasks
        - Understand
      summary: Create Assistant Task Action
  /understand/Assistants/{AssistantSid}/Tasks/{TaskSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Statistics
        - Tasks
        - Understand
      summary: Retrieve Assistant Task Statistics
tags:
  - name: PreviewDeployedDevicesCertificate
  - name: PreviewDeployedDevicesDeployment
  - name: PreviewDeployedDevicesDevice
  - name: PreviewDeployedDevicesFleet
  - name: PreviewDeployedDevicesKey
  - name: PreviewHostedNumbersAuthorizationDocument
  - name: PreviewHostedNumbersDependentHostedNumberOrder
  - name: PreviewHostedNumbersHostedNumberOrder
  - null
  - null
  - null
  - null
  - name: PreviewSyncDocument
  - name: PreviewSyncDocumentPermission
  - name: PreviewSyncService
  - name: PreviewSyncSyncList
  - name: PreviewSyncSyncListItem
  - name: PreviewSyncSyncListPermission
  - name: PreviewSyncSyncMap
  - name: PreviewSyncSyncMapItem
  - name: PreviewSyncSyncMapPermission
  - name: Assistants
  - name: Actions
  - name: Actions
  - name: PreviewUnderstandDialogue
  - name: PreviewUnderstandField
  - name: PreviewUnderstandFieldType
  - name: PreviewUnderstandFieldValue
  - name: PreviewUnderstandModelBuild
  - name: PreviewUnderstandQuery
  - name: PreviewUnderstandSample
  - name: PreviewUnderstandStyleSheet
  - name: PreviewUnderstandTask
  - name: PreviewUnderstandTaskActions
  - name: PreviewUnderstandTaskStatistics
  - name: PreviewWirelessCommand
  - name: PreviewWirelessRatePlan
  - name: PreviewWirelessSim
  - name: PreviewWirelessUsage
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio
