info:
  title: Twilio - Autopilot
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Assistants/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
    post:
      description: ''
      tags:
        - Assistants
        - Sid
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
  /v1/Assistants:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
    post:
      description: ''
      tags:
        - Assistants
        - Sid
  /v1/Assistants/{AssistantSid}/Defaults:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
  /v1/Assistants/{AssistantSid}/Dialogues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
  /v1/Assistants/{AssistantSid}/Dialogues:
    description: 'TODO: Resource-level docs'
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
  /v1/Assistants/{AssistantSid}/FieldTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
  /v1/Assistants/{AssistantSid}/FieldTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
  /v1/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
  /v1/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
  /v1/Assistants/{AssistantSid}/ModelBuilds/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
  /v1/Assistants/{AssistantSid}/ModelBuilds:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
  /v1/Assistants/{AssistantSid}/Queries/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
  /v1/Assistants/{AssistantSid}/Queries:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
  /v1/Assistants/Restore:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
  /v1/Assistants/{AssistantSid}/StyleSheet:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns Style sheet JSON object for the Assistant
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
    post:
      description: Updates the style sheet for an Assistant identified by `assistant_sid`.
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
  /v1/Assistants/{AssistantSid}/Tasks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
  /v1/Assistants/{AssistantSid}/Tasks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Actions:
    description: 'TODO: Resource-level docs'
    get:
      description: Returns JSON actions for the Task.
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
        - Actions
    post:
      description: >-
        Updates the actions of an Task identified by {TaskSid} or
        {TaskUniqueName}.
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
        - Actions
  /v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
        - Actions
        - Statistics
  /v1/Assistants/{AssistantSid}/Webhooks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
        - Actions
        - Statistics
        - Webhooks
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
        - Actions
        - Statistics
        - Webhooks
    delete:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
        - Actions
        - Statistics
        - Webhooks
  /v1/Assistants/{AssistantSid}/Webhooks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
        - Actions
        - Statistics
        - Webhooks
    post:
      description: ''
      tags:
        - Assistants
        - Sid
        - Assistant
        - Defaults
        - Dialogues
        - Tasks
        - Task
        - Fields
        - Field
        - Types
        - Type
        - Values
        - Model
        - Builds
        - Queries
        - Restore
        - Samples
        - Style
        - Sheet
        - Actions
        - Statistics
        - Webhooks
tags:
  - name: AutopilotV1Assistant
  - name: AutopilotV1Defaults
  - name: AutopilotV1Dialogue
  - name: AutopilotV1Field
  - name: AutopilotV1FieldType
  - name: AutopilotV1FieldValue
  - name: AutopilotV1ModelBuild
  - name: AutopilotV1Query
  - name: AutopilotV1RestoreAssistant
  - name: AutopilotV1Sample
  - name: AutopilotV1StyleSheet
  - name: AutopilotV1Task
  - name: AutopilotV1TaskActions
  - name: AutopilotV1TaskStatistics
  - name: AutopilotV1Webhook
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio
