info:
  title: Twilio - Bulkexports
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Exports/{ResourceType}/Days/{Day}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Day.
      tags:
        - Days
        - Exports
        - Fetch
        - Resources
        - Types
      summary: Fetch Export Day
  /v1/Exports/{ResourceType}/Days:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Days for a resource.
      tags:
        - Days
        - Exports
        - Resources
        - Types
      summary: Retrieve Export Days
  /v1/Exports/{ResourceType}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Export.
      tags:
        - Exports
        - Resources
        - Types
      summary: Retrieve Export
  /v1/Exports:
    description: 'TODO: Resource-level docs'
  /v1/Exports/{ResourceType}/Configuration:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Export Configuration.
      tags:
        - Configurations
        - Exports
        - Resources
        - Types
      summary: Retrieve Export Configuration
    post:
      description: Update a specific Export Configuration.
      tags:
        - Configurations
        - Exports
        - Resources
        - Types
      summary: Update Export Configuration
  /v1/Exports/{ResourceType}/Jobs:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Exports
        - Jobs
        - Resources
        - Types
      summary: Retrieve Export Jobs
    post:
      description: ''
      tags:
        - Exports
        - Jobs
        - Resources
        - Types
      summary: Create Export Job
  /v1/Exports/Jobs/{JobSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Exports
        - Jobs
      summary: Retrieve Export Job
    delete:
      description: ''
      tags:
        - Exports
        - Jobs
      summary: Delete Export Job
  /v1/Exports/Jobs:
    description: 'TODO: Resource-level docs'
tags:
  - name: BulkexportsV1Day
  - name: BulkexportsV1Export
  - name: BulkexportsV1ExportConfiguration
  - name: BulkexportsV1ExportCustomJob
  - name: BulkexportsV1Job
x-maturity:
  - name: GA
    description: This product is G
