info:
  title: Twilio - Frontline
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Users/{Sid}:
    description: A User resource represents a frontline user.
    get:
      description: Fetch a frontline user
      tags:
        - Users
        - Sid
    post:
      description: Update an existing frontline user
      tags:
        - Users
        - Sid
tags:
  - name: FrontlineV1User
x-maturity:
  - name: Beta
    description: PLEASE NOTE that this is a Beta product that is subject to change. U
