info:
  title: Twilio - Intelligence
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Transcripts/{Sid}/Media:
    description: 'TODO: Resource-level docs'
    get:
      description: Get download URLs for media if possible
      tags:
        - Media
        - Transcripts
      summary: Retrieve Transcripts Sid Media
  /v2/Transcripts/{TranscriptSid}/OperatorResults:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of Operator Results for the given Transcript.
      tags:
        - Operator
        - Results
        - Transcripts
      summary: Retrieve Transcripts Transcript Sid Operator Results
  /v2/Transcripts/{TranscriptSid}/OperatorResults/{OperatorSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Operator Result for the given Transcript.
      tags:
        - Operator
        - Results
        - Transcripts
      summary: Retrieve Transcripts Transcript Sid Operator Results Operator Sid
  /v2/Transcripts/{TranscriptSid}/Sentences:
    description: 'TODO: Resource-level docs'
    get:
      description: Get all Transcript Sentences by TranscriptSid
      tags:
        - Sentences
        - Transcripts
      summary: Retrieve Transcripts Transcript Sid Sentences
  /v2/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Service for the given Account
      tags:
        - Services
      summary: Create Services
    get:
      description: Retrieves a list of all Services for an account.
      tags:
        - Services
      summary: Retrieve Services
  /v2/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Service.
      tags:
        - Services
      summary: Delete Services Sid
    get:
      description: Fetch a specific Service.
      tags:
        - Services
      summary: Retrieve Services Sid
    post:
      description: Update a specific Service.
      tags:
        - Services
      summary: Create Services Sid
  /v2/Transcripts:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Transcript for the service
      tags:
        - Transcripts
      summary: Create Transcripts
    get:
      description: Retrieve a list of Transcripts for a given service.
      tags:
        - Transcripts
      summary: Retrieve Transcripts
  /v2/Transcripts/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Transcript.
      tags:
        - Transcripts
      summary: Retrieve Transcripts Sid
    delete:
      description: Delete a specific Transcript.
      tags:
        - Transcripts
      summary: Delete Transcripts Sid
tags:
  - name: IntelligenceV2Media
  - name: IntelligenceV2OperatorResult
  - name: IntelligenceV2Sentence
  - name: IntelligenceV2Service
  - name: IntelligenceV2Transcript
x-maturity:
  - name: Beta
    description: PLEASE NOTE that this is a Beta product that is subject to change. U
