info:
  title: Twilio - Ip_messaging
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Services/{ServiceSid}/Bindings:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
  /v2/Services/{ServiceSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
  /v2/Services/{ServiceSid}/Channels/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
  /v2/Services/{ServiceSid}/Channels:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Webhooks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Webhooks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
  /v2/Credentials:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
  /v2/Credentials/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Invites/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Invites:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Members/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Members:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Messages/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
  /v2/Services/{ServiceSid}/Channels/{ChannelSid}/Messages:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
  /v2/Services/{ServiceSid}/Roles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
  /v2/Services/{ServiceSid}/Roles:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
  /v2/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
  /v2/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
  /v2/Services/{ServiceSid}/Users/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
  /v2/Services/{ServiceSid}/Users:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
  /v2/Services/{ServiceSid}/Users/{UserSid}/Bindings:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
        - User
  /v2/Services/{ServiceSid}/Users/{UserSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
        - User
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
        - User
  /v2/Services/{ServiceSid}/Users/{UserSid}/Channels:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
        - User
  /v2/Services/{ServiceSid}/Users/{UserSid}/Channels/{ChannelSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
        - User
    delete:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
        - User
    post:
      description: ''
      tags:
        - Services
        - Service
        - Sid
        - Bindings
        - Channels
        - Channel
        - Webhooks
        - Credentials
        - Invites
        - Members
        - Messages
        - Roles
        - Users
        - User
tags:
  - name: IpMessagingV2Binding
  - name: IpMessagingV2Channel
  - name: IpMessagingV2Credential
  - name: IpMessagingV2Invite
  - name: IpMessagingV2Member
  - name: IpMessagingV2Message
  - name: IpMessagingV2Role
  - name: IpMessagingV2Service
  - name: IpMessagingV2User
  - name: IpMessagingV2UserBinding
  - name: IpMessagingV2UserChannel
  - name: IpMessagingV2Webhook
x-maturity:
  - name: GA
    description: This product is G
