info:
  title: Twilio - Messaging
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/AlphaSenders:
    description: >-
      A Messaging Service resource to add, fetch or remove an Alpha Sender ID
      from a Messaging Service.
    post:
      description: ''
      tags:
        - Alpha
        - Senders
        - Services
      summary: Create Services Service Sid Alpha Senders
    get:
      description: ''
      tags:
        - Alpha
        - Senders
        - Services
      summary: Retrieve Services Service Sid Alpha Senders
  /v1/Services/{ServiceSid}/AlphaSenders/{Sid}:
    description: >-
      A Messaging Service resource to add, fetch or remove an Alpha Sender ID
      from a Messaging Service.
    get:
      description: ''
      tags:
        - Alpha
        - Senders
        - Services
      summary: Retrieve Services Service Sid Alpha Senders Sid
    delete:
      description: ''
      tags:
        - Alpha
        - Senders
        - Services
      summary: Delete Services Service Sid Alpha Senders Sid
  /v1/a2p/BrandRegistrations/{BrandRegistrationSid}/SmsOtp:
    description: >-
      A Messaging Service resource to retry OTP verification for Sole Proprietor
      Brand Registrations.
    post:
      description: ''
      tags:
        - A2p
        - Brands
        - Registrations
        - SMS
      summary: Create A2p Brand Registrations Brand Registration Sid Sms Otp
  /v1/a2p/BrandRegistrations/{Sid}:
    description: A Messaging Service resource to add and fetch Brand Registrations.
    get:
      description: ''
      tags:
        - A2p
        - Brands
        - Registrations
      summary: Retrieve A2p Brand Registrations Sid
    post:
      description: ''
      tags:
        - A2p
        - Brands
        - Registrations
      summary: Create A2p Brand Registrations Sid
  /v1/a2p/BrandRegistrations:
    description: A Messaging Service resource to add and fetch Brand Registrations.
    get:
      description: ''
      tags:
        - A2p
        - Brands
        - Registrations
      summary: Retrieve A2p Brand Registrations
    post:
      description: ''
      tags:
        - A2p
        - Brands
        - Registrations
      summary: Create A2p Brand Registrations
  /v1/a2p/BrandRegistrations/{BrandSid}/Vettings:
    description: A Messaging Service resource to add and get Brand Vettings.
    post:
      description: ''
      tags:
        - A2p
        - Brands
        - Registrations
        - Vettings
      summary: Create A2p Brand Registrations Brand Sid Vettings
    get:
      description: ''
      tags:
        - A2p
        - Brands
        - Registrations
        - Vettings
      summary: Retrieve A2p Brand Registrations Brand Sid Vettings
  /v1/a2p/BrandRegistrations/{BrandSid}/Vettings/{BrandVettingSid}:
    description: A Messaging Service resource to add and get Brand Vettings.
    get:
      description: ''
      tags:
        - A2p
        - Brands
        - Registrations
        - Vettings
      summary: Retrieve A2p Brand Registrations Brand Sid Vettings Brand Vetting Sid
  /v1/Services/{MessagingServiceSid}/ChannelSenders:
    description: >-
      A Messaging Service resource to read, fetch all Channel Senders associated
      with a Messaging Service.
    get:
      description: ''
      tags:
        - Channels
        - Messaging
        - Senders
        - Services
      summary: Retrieve Services Messaging Service Sid Channel Senders
  /v1/Services/{MessagingServiceSid}/ChannelSenders/{Sid}:
    description: >-
      A Messaging Service resource to read, fetch all Channel Senders associated
      with a Messaging Service.
    get:
      description: ''
      tags:
        - Channels
        - Messaging
        - Senders
        - Services
      summary: Retrieve Services Messaging Service Sid Channel Senders Sid
  /v1/Deactivations:
    description: >-
      A Deactivation resource to retrieve a list of United States phone numbers
      that have been deactivated by mobile carriers on a specific date.
    get:
      description: >-
        Fetch a list of all United States numbers that have been deactivated on
        a specific date.
      tags:
        - Deactivations
      summary: Retrieve Deactivations
  /v1/LinkShortening/Domains/{DomainSid}/Certificate:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Certificates
        - Domains
        - Link
        - Shortening
      summary: Create Link Shortening Domains Domain Sid Certificate
    get:
      description: ''
      tags:
        - Certificates
        - Domains
        - Link
        - Shortening
      summary: Retrieve Link Shortening Domains Domain Sid Certificate
    delete:
      description: ''
      tags:
        - Certificates
        - Domains
        - Link
        - Shortening
      summary: Delete Link Shortening Domains Domain Sid Certificate
  /v1/LinkShortening/Domains/{DomainSid}/Config:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Configurations
        - Domains
        - Link
        - Shortening
      summary: Create Link Shortening Domains Domain Sid Config
    get:
      description: ''
      tags:
        - Configurations
        - Domains
        - Link
        - Shortening
      summary: Retrieve Link Shortening Domains Domain Sid Config
  /v1/LinkShortening/MessagingService/{MessagingServiceSid}/DomainConfig:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Configurations
        - Domains
        - Link
        - Messaging
        - Services
        - Shortening
      summary: >-
        Retrieve Link Shortening Messaging Service Messaging Service Sid Domain
        Config
  /v1/Services/PreregisteredUsa2p:
    description: Resource to associate preregistered campaign with Messaging Service.
    post:
      description: ''
      tags:
        - Pre Registered
        - Services
      summary: Create Services Preregistered Usa2p
  /v1/LinkShortening/Domains/{DomainSid}/MessagingServices/{MessagingServiceSid}:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Domains
        - Link
        - Messaging
        - Services
        - Shortening
      summary: >-
        Create Link Shortening Domains Domain Sid Messaging Services Messaging
        Service Sid
    delete:
      description: ''
      tags:
        - Domains
        - Link
        - Messaging
        - Services
        - Shortening
      summary: >-
        Delete Link Shortening Domains Domain Sid Messaging Services Messaging
        Service Sid
  /v1/LinkShortening/MessagingServices/{MessagingServiceSid}/Domain:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Domains
        - Link
        - Messaging
        - Services
        - Shortening
      summary: Retrieve Link Shortening Messaging Services Messaging Service Sid Domain
  /v1/Services/{ServiceSid}/PhoneNumbers:
    description: >-
      A Messaging Service resource to add, fetch or remove phone numbers from a
      Messaging Service.
    post:
      description: ''
      tags:
        - Numbers
        - Phone
        - Services
      summary: Create Services Service Sid Phone Numbers
    get:
      description: ''
      tags:
        - Numbers
        - Phone
        - Services
      summary: Retrieve Services Service Sid Phone Numbers
  /v1/Services/{ServiceSid}/PhoneNumbers/{Sid}:
    description: >-
      A Messaging Service resource to add, fetch or remove phone numbers from a
      Messaging Service.
    delete:
      description: ''
      tags:
        - Numbers
        - Phone
        - Services
      summary: Delete Services Service Sid Phone Numbers Sid
    get:
      description: ''
      tags:
        - Numbers
        - Phone
        - Services
      summary: Retrieve Services Service Sid Phone Numbers Sid
  /v1/Services:
    description: >-
      A Messaging Service resource to create, fetch, update, delete or
      add/remove senders from Messaging Services.
    post:
      description: ''
      tags:
        - Services
      summary: Create Services
    get:
      description: ''
      tags:
        - Services
      summary: Retrieve Services
  /v1/Services/{Sid}:
    description: >-
      A Messaging Service resource to create, fetch, update, delete or
      add/remove senders from Messaging Services.
    post:
      description: ''
      tags:
        - Services
      summary: Create Services Sid
    get:
      description: ''
      tags:
        - Services
      summary: Retrieve Services Sid
    delete:
      description: ''
      tags:
        - Services
      summary: Delete Services Sid
  /v1/Services/{ServiceSid}/ShortCodes:
    description: >-
      A Messaging Service resource to add, fetch or remove short code numbers
      from a Messaging Service.
    post:
      description: ''
      tags:
        - Codes
        - Services
      summary: Create Services Service Sid Short Codes
    get:
      description: ''
      tags:
        - Codes
        - Services
      summary: Retrieve Services Service Sid Short Codes
  /v1/Services/{ServiceSid}/ShortCodes/{Sid}:
    description: >-
      A Messaging Service resource to add, fetch or remove short code numbers
      from a Messaging Service.
    delete:
      description: ''
      tags:
        - Codes
        - Services
      summary: Delete Services Service Sid Short Codes Sid
    get:
      description: ''
      tags:
        - Codes
        - Services
      summary: Retrieve Services Service Sid Short Codes Sid
  /v1/Tollfree/Verifications/{Sid}:
    description: A Messaging resource to add and fetch Tollfree Verifications.
    get:
      description: ''
      tags:
        - Toll Free
        - Verifications
      summary: Retrieve Tollfree Verifications Sid
    post:
      description: ''
      tags:
        - Toll Free
        - Verifications
      summary: Create Tollfree Verifications Sid
    delete:
      description: ''
      tags:
        - Toll Free
        - Verifications
      summary: Delete Tollfree Verifications Sid
  /v1/Tollfree/Verifications:
    description: A Messaging resource to add and fetch Tollfree Verifications.
    get:
      description: ''
      tags:
        - Toll Free
        - Verifications
      summary: Retrieve Tollfree Verifications
    post:
      description: ''
      tags:
        - Toll Free
        - Verifications
      summary: Create Tollfree Verifications
  /v1/Services/{MessagingServiceSid}/Compliance/Usa2p:
    description: A service for (fetch/create/delete) A2P Campaign for a Messaging Service
    post:
      description: ''
      tags:
        - Compliance
        - Messaging
        - Services
      summary: Create Services Messaging Service Sid Compliance Usa2p
    get:
      description: ''
      tags:
        - Compliance
        - Messaging
        - Services
      summary: Retrieve Services Messaging Service Sid Compliance Usa2p
  /v1/Services/{MessagingServiceSid}/Compliance/Usa2p/{Sid}:
    description: A service for (fetch/create/delete) A2P Campaign for a Messaging Service
    delete:
      description: ''
      tags:
        - Compliance
        - Messaging
        - Services
      summary: Delete Services Messaging Service Sid Compliance Usa2p Sid
    get:
      description: ''
      tags:
        - Compliance
        - Messaging
        - Services
      summary: Retrieve Services Messaging Service Sid Compliance Usa2p Sid
  /v1/Services/{MessagingServiceSid}/Compliance/Usa2p/Usecases:
    description: >-
      Messaging Service Use Case resource. Fetch possible use cases for service.
      The Use Cases API returns an empty list if there is an issue with the
      customer's A2P brand registration. This Brand cannot register any campaign
      use cases. Customers are requested to contact support with their A2P brand
      information.
    get:
      description: ''
      tags:
        - Compliance
        - Messaging
        - Services
        - Use Cases
      summary: Retrieve Services Messaging Service Sid Compliance Usa2p Usecases
  /v1/Services/Usecases:
    description: Use Case resource. Fetch possible use cases for a Messaging Service.
    get:
      description: ''
      tags:
        - Services
        - Use Cases
      summary: Retrieve Services Usecases
tags:
  - name: MessagingV1AlphaSender
  - name: MessagingV1BrandRegistration
  - name: MessagingV1BrandRegistrationOtp
  - name: MessagingV1BrandVetting
  - name: MessagingV1ChannelSender
  - name: MessagingV1Deactivations
  - name: MessagingV1DomainCerts
  - name: MessagingV1DomainConfig
  - name: MessagingV1DomainConfigMessagingService
  - name: MessagingV1ExternalCampaign
  - name: MessagingV1LinkshorteningMessagingService
  - name: MessagingV1LinkshorteningMessagingServiceDomainAssociation
  - name: MessagingV1PhoneNumber
  - name: MessagingV1Service
  - name: MessagingV1ShortCode
  - name: MessagingV1TollfreeVerification
  - name: MessagingV1UsAppToPerson
  - name: MessagingV1UsAppToPersonUsecase
  - name: MessagingV1Usecase
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: PLEASE NOTE that this is a Beta product that is subject to change. U
