info:
  title: Twilio - Microvisor
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Configs:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Configs for an Account.
      tags:
        - Configurations
      summary: Retrieve Configs
    post:
      description: Create a config for an Account.
      tags:
        - Configurations
      summary: Create Configs
  /v1/Configs/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Config for an Account.
      tags:
        - Configurations
        - Keys
      summary: Retrieve Configs Key
    post:
      description: Update a config for an Account.
      tags:
        - Configurations
        - Keys
      summary: Create Configs Key
    delete:
      description: Delete a config for an Account.
      tags:
        - Configurations
        - Keys
      summary: Delete Configs Key
  /v1/Secrets:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Secrets for an Account.
      tags:
        - Secrets
      summary: Retrieve Secrets
    post:
      description: Create a secret for an Account.
      tags:
        - Secrets
      summary: Create Secrets
  /v1/Secrets/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Secret for an Account.
      tags:
        - Keys
        - Secrets
      summary: Retrieve Secrets Key
    post:
      description: Update a secret for an Account.
      tags:
        - Keys
        - Secrets
      summary: Create Secrets Key
    delete:
      description: Delete a secret for an Account.
      tags:
        - Keys
        - Secrets
      summary: Delete Secrets Key
  /v1/Apps:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Apps for an Account.
      tags:
        - Applications
      summary: Retrieve Apps
  /v1/Apps/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific App.
      tags:
        - Applications
      summary: Retrieve Apps Sid
    delete:
      description: Delete a specific App.
      tags:
        - Applications
      summary: Delete Apps Sid
  /v1/Apps/{AppSid}/Manifest:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve the Manifest for an App.
      tags:
        - Applications
        - Manifests
      summary: Retrieve Apps App Sid Manifest
  /v1/Devices:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Devices registered with the Account.
      tags:
        - Devices
      summary: Retrieve Devices
  /v1/Devices/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Device.
      tags:
        - Devices
      summary: Retrieve Devices Sid
    post:
      description: Update a specific Device.
      tags:
        - Devices
      summary: Create Devices Sid
  /v1/Devices/{DeviceSid}/Configs:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Configs for a Device.
      tags:
        - Configurations
        - Device
        - Devices
      summary: Retrieve Devices Device Sid Configs
    post:
      description: Create a config for a Microvisor Device.
      tags:
        - Configurations
        - Device
        - Devices
      summary: Create Devices Device Sid Configs
  /v1/Devices/{DeviceSid}/Configs/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Config for a Device.
      tags:
        - Configurations
        - Device
        - Devices
        - Keys
      summary: Retrieve Devices Device Sid Configs Key
    post:
      description: Update a config for a Microvisor Device.
      tags:
        - Configurations
        - Device
        - Devices
        - Keys
      summary: Create Devices Device Sid Configs Key
    delete:
      description: Delete a config for a Microvisor Device.
      tags:
        - Configurations
        - Device
        - Devices
        - Keys
      summary: Delete Devices Device Sid Configs Key
  /v1/Devices/{DeviceSid}/Secrets:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Secrets for a Device.
      tags:
        - Device
        - Devices
        - Secrets
      summary: Retrieve Devices Device Sid Secrets
    post:
      description: Create a secret for a Microvisor Device.
      tags:
        - Device
        - Devices
        - Secrets
      summary: Create Devices Device Sid Secrets
  /v1/Devices/{DeviceSid}/Secrets/{Key}:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a Secret for a Device.
      tags:
        - Device
        - Devices
        - Keys
        - Secrets
      summary: Retrieve Devices Device Sid Secrets Key
    post:
      description: Update a secret for a Microvisor Device.
      tags:
        - Device
        - Devices
        - Keys
        - Secrets
      summary: Create Devices Device Sid Secrets Key
    delete:
      description: Delete a secret for a Microvisor Device.
      tags:
        - Device
        - Devices
        - Keys
        - Secrets
      summary: Delete Devices Device Sid Secrets Key
tags:
  - name: MicrovisorV1AccountConfig
  - name: MicrovisorV1AccountSecret
  - name: MicrovisorV1App
  - name: MicrovisorV1AppManifest
  - name: MicrovisorV1Device
  - name: MicrovisorV1DeviceConfig
  - name: MicrovisorV1DeviceSecret
x-maturity:
  - name: Preview
    description: >-
      PLEASE NOTE that this is a Preview product that is subject to change. Use
      it with caution. If you currently do not have developer preview access,
      please contact https://www.twilio
