info:
  title: Twilio - Notify
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Bindings/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Bindings
        - Services
      summary: Retrieve Services Service Sid Bindings Sid
    delete:
      description: ''
      tags:
        - Bindings
        - Services
      summary: Delete Services Service Sid Bindings Sid
  /v1/Services/{ServiceSid}/Bindings:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Bindings
        - Services
      summary: Create Services Service Sid Bindings
    get:
      description: ''
      tags:
        - Bindings
        - Services
      summary: Retrieve Services Service Sid Bindings
  /v1/Credentials:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Credentials
      summary: Retrieve Credentials
    post:
      description: ''
      tags:
        - Credentials
      summary: Create Credentials
  /v1/Credentials/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Credentials
      summary: Retrieve Credentials Sid
    post:
      description: ''
      tags:
        - Credentials
      summary: Create Credentials Sid
    delete:
      description: ''
      tags:
        - Credentials
      summary: Delete Credentials Sid
  /v1/Services/{ServiceSid}/Notifications:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Notifications
        - Services
      summary: Create Services Service Sid Notifications
  /v1/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
      summary: Create Services
    get:
      description: ''
      tags:
        - Services
      summary: Retrieve Services
  /v1/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: ''
      tags:
        - Services
      summary: Delete Services Sid
    get:
      description: ''
      tags:
        - Services
      summary: Retrieve Services Sid
    post:
      description: ''
      tags:
        - Services
      summary: Create Services Sid
tags:
  - name: NotifyV1Binding
  - name: NotifyV1Credential
  - name: NotifyV1Notification
  - name: NotifyV1Service
x-maturity:
  - name: Beta
    description: PLEASE NOTE that this is a Beta product that is subject to change. U
