info:
  title: Twilio - Numbers
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/HostedNumber/AuthorizationDocuments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific AuthorizationDocument.
      tags:
        - Authorization
        - Documents
        - Hosted
        - Numbers
      summary: Retrieve Hosted Number Authorization Documents Sid
    delete:
      description: Cancel the AuthorizationDocument request.
      tags:
        - Authorization
        - Documents
        - Hosted
        - Numbers
      summary: Delete Hosted Number Authorization Documents Sid
  /v2/HostedNumber/AuthorizationDocuments:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of AuthorizationDocuments belonging to the account
        initiating the request.
      tags:
        - Authorization
        - Documents
        - Hosted
        - Numbers
      summary: Retrieve Hosted Number Authorization Documents
    post:
      description: >-
        Create an AuthorizationDocument for authorizing the hosting of phone
        number capabilities on Twilio's platform.
      tags:
        - Authorization
        - Documents
        - Hosted
        - Numbers
      summary: Create Hosted Number Authorization Documents
  /v2/HostedNumber/Orders/Bulk/{BulkHostingSid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific BulkHostedNumberOrder.
      tags:
        - Bulk
        - Hosted
        - Hosting
        - Numbers
        - Orders
      summary: Retrieve Hosted Number Orders Bulk Bulk Hosting Sid
  /v2/HostedNumber/Orders/Bulk:
    description: 'TODO: Resource-level docs'
  /v2/RegulatoryCompliance/Bundles:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Bundle.
      tags:
        - Bundles
        - Compliance
        - Regulatory
      summary: Create Regulatory Compliance Bundles
    get:
      description: Retrieve a list of all Bundles for an account.
      tags:
        - Bundles
        - Compliance
        - Regulatory
      summary: Retrieve Regulatory Compliance Bundles
  /v2/RegulatoryCompliance/Bundles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Bundle instance.
      tags:
        - Bundles
        - Compliance
        - Regulatory
      summary: Retrieve Regulatory Compliance Bundles Sid
    post:
      description: Updates a Bundle in an account.
      tags:
        - Bundles
        - Compliance
        - Regulatory
      summary: Create Regulatory Compliance Bundles Sid
    delete:
      description: Delete a specific Bundle.
      tags:
        - Bundles
        - Compliance
        - Regulatory
      summary: Delete Regulatory Compliance Bundles Sid
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Copies:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Creates a new copy of a Bundle. It will internally create copies of all
        the bundle items (identities and documents) of the original bundle
      tags:
        - Bundles
        - Compliance
        - Copies
        - Regulatory
      summary: Create Regulatory Compliance Bundles Bundle Sid Copies
    get:
      description: Retrieve a list of all Bundles Copies for a Bundle.
      tags:
        - Bundles
        - Compliance
        - Copies
        - Regulatory
      summary: Retrieve Regulatory Compliance Bundles Bundle Sid Copies
  /v2/HostedNumber/AuthorizationDocuments/{SigningDocumentSid}/DependentHostedNumberOrders:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of dependent HostedNumberOrders belonging to the
        AuthorizationDocument.
      tags:
        - Authorization
        - Dependent
        - Documents
        - Hosted
        - Numbers
        - Orders
        - Signing
      summary: >-
        Retrieve Hosted Number Authorization Documents Signing Document Sid
        Dependent Hosted Number Orders
  /v2/RegulatoryCompliance/EndUsers:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new End User.
      tags:
        - Compliance
        - Regulatory
        - Users
      summary: Create Regulatory Compliance End Users
    get:
      description: Retrieve a list of all End User for an account.
      tags:
        - Compliance
        - Regulatory
        - Users
      summary: Retrieve Regulatory Compliance End Users
  /v2/RegulatoryCompliance/EndUsers/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific End User Instance.
      tags:
        - Compliance
        - Regulatory
        - Users
      summary: Retrieve Regulatory Compliance End Users Sid
    post:
      description: Update an existing End User.
      tags:
        - Compliance
        - Regulatory
        - Users
      summary: Create Regulatory Compliance End Users Sid
    delete:
      description: Delete a specific End User.
      tags:
        - Compliance
        - Regulatory
        - Users
      summary: Delete Regulatory Compliance End Users Sid
  /v2/RegulatoryCompliance/EndUserTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all End-User Types.
      tags:
        - Compliance
        - Regulatory
        - Types
        - Users
      summary: Retrieve Regulatory Compliance End User Types
  /v2/RegulatoryCompliance/EndUserTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific End-User Type Instance.
      tags:
        - Compliance
        - Regulatory
        - Types
        - Users
      summary: Retrieve Regulatory Compliance End User Types Sid
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Evaluations:
    description: 'TODO: Resource-level docs'
    post:
      description: Creates an evaluation for a bundle
      tags:
        - Bundles
        - Compliance
        - Evaluations
        - Regulatory
      summary: Create Regulatory Compliance Bundles Bundle Sid Evaluations
    get:
      description: Retrieve a list of Evaluations associated to the Bundle resource.
      tags:
        - Bundles
        - Compliance
        - Evaluations
        - Regulatory
      summary: Retrieve Regulatory Compliance Bundles Bundle Sid Evaluations
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/Evaluations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Evaluation Instance.
      tags:
        - Bundles
        - Compliance
        - Evaluations
        - Regulatory
      summary: Retrieve Regulatory Compliance Bundles Bundle Sid Evaluations Sid
  /v2/HostedNumber/Orders/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific HostedNumberOrder.
      tags:
        - Hosted
        - Numbers
        - Orders
      summary: Retrieve Hosted Number Orders Sid
    delete:
      description: >-
        Cancel the HostedNumberOrder (only available when the status is in
        `received`).
      tags:
        - Hosted
        - Numbers
        - Orders
      summary: Delete Hosted Number Orders Sid
  /v2/HostedNumber/Orders:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Retrieve a list of HostedNumberOrders belonging to the account
        initiating the request.
      tags:
        - Hosted
        - Numbers
        - Orders
      summary: Retrieve Hosted Number Orders
    post:
      description: Host a phone number's capability on Twilio's platform.
      tags:
        - Hosted
        - Numbers
        - Orders
      summary: Create Hosted Number Orders
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ItemAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - Assignments
        - Bundles
        - Compliance
        - Items
        - Regulatory
      summary: Create Regulatory Compliance Bundles Bundle Sid Item Assignments
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - Assignments
        - Bundles
        - Compliance
        - Items
        - Regulatory
      summary: Retrieve Regulatory Compliance Bundles Bundle Sid Item Assignments
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ItemAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - Assignments
        - Bundles
        - Compliance
        - Items
        - Regulatory
      summary: Retrieve Regulatory Compliance Bundles Bundle Sid Item Assignments Sid
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - Assignments
        - Bundles
        - Compliance
        - Items
        - Regulatory
      summary: Delete Regulatory Compliance Bundles Bundle Sid Item Assignments Sid
  /v2/RegulatoryCompliance/Regulations:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Regulations.
      tags:
        - Compliance
        - Regulations
        - Regulatory
      summary: Retrieve Regulatory Compliance Regulations
  /v2/RegulatoryCompliance/Regulations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Regulation Instance.
      tags:
        - Compliance
        - Regulations
        - Regulatory
      summary: Retrieve Regulatory Compliance Regulations Sid
  /v2/RegulatoryCompliance:
    description: 'TODO: Resource-level docs'
  /v2/RegulatoryCompliance/Bundles/{BundleSid}/ReplaceItems:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Replaces all bundle items in the target bundle (specified in the path)
        with all the bundle items of the source bundle (specified by the
        from_bundle_sid body param)
      tags:
        - Bundles
        - Compliance
        - Items
        - Regulatory
        - Replace
      summary: Create Regulatory Compliance Bundles Bundle Sid Replace Items
  /v2/RegulatoryCompliance/SupportingDocuments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Supporting Document.
      tags:
        - Compliance
        - Documents
        - Regulatory
        - Supporting
      summary: Create Regulatory Compliance Supporting Documents
    get:
      description: Retrieve a list of all Supporting Document for an account.
      tags:
        - Compliance
        - Documents
        - Regulatory
        - Supporting
      summary: Retrieve Regulatory Compliance Supporting Documents
  /v2/RegulatoryCompliance/SupportingDocuments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Supporting Document Instance.
      tags:
        - Compliance
        - Documents
        - Regulatory
        - Supporting
      summary: Retrieve Regulatory Compliance Supporting Documents Sid
    post:
      description: Update an existing Supporting Document.
      tags:
        - Compliance
        - Documents
        - Regulatory
        - Supporting
      summary: Create Regulatory Compliance Supporting Documents Sid
    delete:
      description: Delete a specific Supporting Document.
      tags:
        - Compliance
        - Documents
        - Regulatory
        - Supporting
      summary: Delete Regulatory Compliance Supporting Documents Sid
  /v2/RegulatoryCompliance/SupportingDocumentTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Supporting Document Types.
      tags:
        - Compliance
        - Documents
        - Regulatory
        - Supporting
        - Types
      summary: Retrieve Regulatory Compliance Supporting Document Types
  /v2/RegulatoryCompliance/SupportingDocumentTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Supporting Document Type Instance.
      tags:
        - Compliance
        - Documents
        - Regulatory
        - Supporting
        - Types
      summary: Retrieve Regulatory Compliance Supporting Document Types Sid
tags:
  - name: NumbersV2AuthorizationDocument
  - name: NumbersV2BulkHostedNumberOrder
  - name: NumbersV2Bundle
  - name: NumbersV2BundleCopy
  - name: NumbersV2DependentHostedNumberOrder
  - name: NumbersV2EndUser
  - name: NumbersV2EndUserType
  - name: NumbersV2Evaluation
  - name: NumbersV2HostedNumberOrder
  - name: NumbersV2ItemAssignment
  - name: NumbersV2Regulation
  - name: NumbersV2ReplaceItems
  - name: NumbersV2SupportingDocument
  - name: NumbersV2SupportingDocumentType
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: PLEASE NOTE that this is a Beta product that is subject to change. U
