info:
  title: Twilio - Routes
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/PhoneNumbers/{PhoneNumber}:
    description: 'TODO: Resource-level docs'
    post:
      description: Assign an Inbound Processing Region to a phone number.
      tags:
        - Phone
        - Numbers
        - Number
    get:
      description: Fetch the Inbound Processing Region assigned to a phone number.
      tags:
        - Phone
        - Numbers
        - Number
  /v2/SipDomains/{SipDomain}:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Phone
        - Numbers
        - Number
        - Sip
        - Domains
        - Domain
    get:
      description: ''
      tags:
        - Phone
        - Numbers
        - Number
        - Sip
        - Domains
        - Domain
  /v2/Trunks/{SipTrunkDomain}:
    description: 'TODO: Resource-level docs'
    post:
      description: Assign an Inbound Processing Region to a SIP Trunk
      tags:
        - Phone
        - Numbers
        - Number
        - Sip
        - Domains
        - Domain
        - Trunks
        - Trunk
    get:
      description: Fetch the Inbound Processing Region assigned to a SIP Trunk.
      tags:
        - Phone
        - Numbers
        - Number
        - Sip
        - Domains
        - Domain
        - Trunks
        - Trunk
tags:
  - name: RoutesV2PhoneNumber
  - name: RoutesV2SipDomain
  - name: RoutesV2Trunk
x-maturity:
  - name: GA
    description: This product is G
