info:
  title: Twilio - Studio
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Flows/{FlowSid}/Executions:
    description: Executions of Studio flows
    get:
      description: Retrieve a list of all Executions for the Flow.
      tags:
        - Executions
        - Flows
      summary: Retrieve Flows Flow Sid Executions
    post:
      description: Triggers a new Execution for the Flow
      tags:
        - Executions
        - Flows
      summary: Create Flows Flow Sid Executions
  /v2/Flows/{FlowSid}/Executions/{Sid}:
    description: Executions of Studio flows
    get:
      description: Retrieve an Execution
      tags:
        - Executions
        - Flows
      summary: Retrieve Flows Flow Sid Executions Sid
    delete:
      description: Delete the Execution and all Steps relating to it.
      tags:
        - Executions
        - Flows
      summary: Delete Flows Flow Sid Executions Sid
    post:
      description: Update the status of an Execution to `ended`.
      tags:
        - Executions
        - Flows
      summary: Create Flows Flow Sid Executions Sid
  /v2/Flows/{FlowSid}/Executions/{ExecutionSid}/Context:
    description: JSON context for executions
    get:
      description: Retrieve the most recent context for an Execution.
      tags:
        - Context
        - Execution
        - Executions
        - Flows
      summary: Retrieve Flows Flow Sid Executions Execution Sid Context
  /v2/Flows/{FlowSid}/Executions/{ExecutionSid}/Steps:
    description: Individual steps within an execution
    get:
      description: Retrieve a list of all Steps for an Execution.
      tags:
        - Execution
        - Executions
        - Flows
        - Steps
      summary: Retrieve Flows Flow Sid Executions Execution Sid Steps
  /v2/Flows/{FlowSid}/Executions/{ExecutionSid}/Steps/{Sid}:
    description: Individual steps within an execution
    get:
      description: Retrieve a Step.
      tags:
        - Execution
        - Executions
        - Flows
        - Steps
      summary: Retrieve Flows Flow Sid Executions Execution Sid Steps Sid
  /v2/Flows/{FlowSid}/Executions/{ExecutionSid}/Steps/{StepSid}/Context:
    description: JSON context for an individual step within an execution
    get:
      description: Retrieve the context for an Execution Step.
      tags:
        - Context
        - Execution
        - Executions
        - Flows
        - Steps
      summary: Retrieve Flows Flow Sid Executions Execution Sid Steps Step Sid Context
  /v2/Flows:
    description: Studio flows
    post:
      description: Create a Flow.
      tags:
        - Flows
      summary: Create Flows
    get:
      description: Retrieve a list of all Flows.
      tags:
        - Flows
      summary: Retrieve Flows
  /v2/Flows/{Sid}:
    description: Studio flows
    post:
      description: Update a Flow.
      tags:
        - Flows
      summary: Create Flows Sid
    get:
      description: Retrieve a specific Flow.
      tags:
        - Flows
      summary: Retrieve Flows Sid
    delete:
      description: Delete a specific Flow.
      tags:
        - Flows
      summary: Delete Flows Sid
  /v2/Flows/{Sid}/Revisions:
    description: Studio flows revisions
    get:
      description: Retrieve a list of all Flows revisions.
      tags:
        - Flows
        - Revisions
      summary: Retrieve Flows Sid Revisions
  /v2/Flows/{Sid}/Revisions/{Revision}:
    description: Studio flows revisions
    get:
      description: Retrieve a specific Flow revision.
      tags:
        - Flows
        - Revisions
      summary: Retrieve Flows Sid Revisions Revision
  /v2/Flows/Validate:
    description: Flow definition validator
    post:
      description: Validate flow JSON definition
      tags:
        - Ate
        - Flows
        - Val
        - Validate
      summary: Create Flows Validate
  /v2/Flows/{Sid}/TestUsers:
    description: Test users of a flow
    get:
      description: Fetch flow test users
      tags:
        - Flows
        - Tests
        - Users
      summary: Retrieve Flows Sid Test Users
    post:
      description: Update flow test users
      tags:
        - Flows
        - Tests
        - Users
      summary: Create Flows Sid Test Users
tags:
  - name: StudioV2Execution
  - name: StudioV2ExecutionContext
  - name: StudioV2ExecutionStep
  - name: StudioV2ExecutionStepContext
  - name: StudioV2Flow
  - name: StudioV2FlowRevision
  - name: StudioV2FlowTestUser
  - name: StudioV2FlowValidate
x-maturity:
  - name: GA
    description: This product is G
