info:
  title: Twilio - Sync
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Services/{ServiceSid}/Documents/{Sid}:
    description: Sync Document objects
    get:
      description: ''
      tags:
        - Documents
        - Services
      summary: Retrieve Services Service Sid Documents Sid
    delete:
      description: ''
      tags:
        - Documents
        - Services
      summary: Delete Services Service Sid Documents Sid
    post:
      description: ''
      tags:
        - Documents
        - Services
      summary: Create Services Service Sid Documents Sid
  /v1/Services/{ServiceSid}/Documents:
    description: Sync Document objects
    post:
      description: ''
      tags:
        - Documents
        - Services
      summary: Create Services Service Sid Documents
    get:
      description: ''
      tags:
        - Documents
        - Services
      summary: Retrieve Services Service Sid Documents
  /v1/Services/{ServiceSid}/Documents/{DocumentSid}/Permissions/{Identity}:
    description: Sync document permissions
    get:
      description: Fetch a specific Sync Document Permission.
      tags:
        - Documents
        - Identity
        - Permissions
        - Services
      summary: >-
        Retrieve Services Service Sid Documents Document Sid Permissions
        Identity
    delete:
      description: Delete a specific Sync Document Permission.
      tags:
        - Documents
        - Identity
        - Permissions
        - Services
      summary: Delete Services Service Sid Documents Document Sid Permissions Identity
    post:
      description: Update an identity's access to a specific Sync Document.
      tags:
        - Documents
        - Identity
        - Permissions
        - Services
      summary: Create Services Service Sid Documents Document Sid Permissions Identity
  /v1/Services/{ServiceSid}/Documents/{DocumentSid}/Permissions:
    description: Sync document permissions
    get:
      description: Retrieve a list of all Permissions applying to a Sync Document.
      tags:
        - Documents
        - Permissions
        - Services
      summary: Retrieve Services Service Sid Documents Document Sid Permissions
  /v1/Services/{Sid}:
    description: Containers for sync objects
    get:
      description: ''
      tags:
        - Services
      summary: Retrieve Services Sid
    delete:
      description: ''
      tags:
        - Services
      summary: Delete Services Sid
    post:
      description: ''
      tags:
        - Services
      summary: Create Services Sid
  /v1/Services:
    description: Containers for sync objects
    post:
      description: ''
      tags:
        - Services
      summary: Create Services
    get:
      description: ''
      tags:
        - Services
      summary: Retrieve Services
  /v1/Services/{ServiceSid}/Streams/{StreamSid}/Messages:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Stream Message.
      tags:
        - Messages
        - Services
        - Stream
        - Streams
      summary: Create Services Service Sid Streams Stream Sid Messages
  /v1/Services/{ServiceSid}/Lists/{Sid}:
    description: Sync list objects
    get:
      description: ''
      tags:
        - Services
      summary: Retrieve Services Service Sid Lists Sid
    delete:
      description: ''
      tags:
        - Services
      summary: Delete Services Service Sid Lists Sid
    post:
      description: ''
      tags:
        - Services
      summary: Create Services Service Sid Lists Sid
  /v1/Services/{ServiceSid}/Lists:
    description: Sync list objects
    post:
      description: ''
      tags:
        - Services
      summary: Create Services Service Sid Lists
    get:
      description: ''
      tags:
        - Services
      summary: Retrieve Services Service Sid Lists
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Items/{Index}:
    description: Items in a sync list
    get:
      description: ''
      tags:
        - Index
        - Items
        - Services
      summary: Retrieve Services Service Sid Lists List Sid Items Index
    delete:
      description: ''
      tags:
        - Index
        - Items
        - Services
      summary: Delete Services Service Sid Lists List Sid Items Index
    post:
      description: ''
      tags:
        - Index
        - Items
        - Services
      summary: Create Services Service Sid Lists List Sid Items Index
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Items:
    description: Items in a sync list
    post:
      description: ''
      tags:
        - Items
        - Services
      summary: Create Services Service Sid Lists List Sid Items
    get:
      description: ''
      tags:
        - Items
        - Services
      summary: Retrieve Services Service Sid Lists List Sid Items
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Permissions/{Identity}:
    description: Permissions for Sync list items
    get:
      description: Fetch a specific Sync List Permission.
      tags:
        - Identity
        - Permissions
        - Services
      summary: Retrieve Services Service Sid Lists List Sid Permissions Identity
    delete:
      description: Delete a specific Sync List Permission.
      tags:
        - Identity
        - Permissions
        - Services
      summary: Delete Services Service Sid Lists List Sid Permissions Identity
    post:
      description: Update an identity's access to a specific Sync List.
      tags:
        - Identity
        - Permissions
        - Services
      summary: Create Services Service Sid Lists List Sid Permissions Identity
  /v1/Services/{ServiceSid}/Lists/{ListSid}/Permissions:
    description: Permissions for Sync list items
    get:
      description: Retrieve a list of all Permissions applying to a Sync List.
      tags:
        - Permissions
        - Services
      summary: Retrieve Services Service Sid Lists List Sid Permissions
  /v1/Services/{ServiceSid}/Maps/{Sid}:
    description: Sync map objects
    get:
      description: ''
      tags:
        - Maps
        - Services
      summary: Retrieve Services Service Sid Maps Sid
    delete:
      description: ''
      tags:
        - Maps
        - Services
      summary: Delete Services Service Sid Maps Sid
    post:
      description: ''
      tags:
        - Maps
        - Services
      summary: Create Services Service Sid Maps Sid
  /v1/Services/{ServiceSid}/Maps:
    description: Sync map objects
    post:
      description: ''
      tags:
        - Maps
        - Services
      summary: Create Services Service Sid Maps
    get:
      description: ''
      tags:
        - Maps
        - Services
      summary: Retrieve Services Service Sid Maps
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Items/{Key}:
    description: Keys in a sync map
    get:
      description: ''
      tags:
        - Items
        - Keys
        - Maps
        - Services
      summary: Retrieve Services Service Sid Maps Map Sid Items Key
    delete:
      description: ''
      tags:
        - Items
        - Keys
        - Maps
        - Services
      summary: Delete Services Service Sid Maps Map Sid Items Key
    post:
      description: ''
      tags:
        - Items
        - Keys
        - Maps
        - Services
      summary: Create Services Service Sid Maps Map Sid Items Key
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Items:
    description: Keys in a sync map
    post:
      description: ''
      tags:
        - Items
        - Maps
        - Services
      summary: Create Services Service Sid Maps Map Sid Items
    get:
      description: ''
      tags:
        - Items
        - Maps
        - Services
      summary: Retrieve Services Service Sid Maps Map Sid Items
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Permissions/{Identity}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Sync Map Permission.
      tags:
        - Identity
        - Maps
        - Permissions
        - Services
      summary: Retrieve Services Service Sid Maps Map Sid Permissions Identity
    delete:
      description: Delete a specific Sync Map Permission.
      tags:
        - Identity
        - Maps
        - Permissions
        - Services
      summary: Delete Services Service Sid Maps Map Sid Permissions Identity
    post:
      description: Update an identity's access to a specific Sync Map.
      tags:
        - Identity
        - Maps
        - Permissions
        - Services
      summary: Create Services Service Sid Maps Map Sid Permissions Identity
  /v1/Services/{ServiceSid}/Maps/{MapSid}/Permissions:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Permissions applying to a Sync Map.
      tags:
        - Maps
        - Permissions
        - Services
      summary: Retrieve Services Service Sid Maps Map Sid Permissions
  /v1/Services/{ServiceSid}/Streams/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Stream.
      tags:
        - Services
        - Streams
      summary: Retrieve Services Service Sid Streams Sid
    delete:
      description: Delete a specific Stream.
      tags:
        - Services
        - Streams
      summary: Delete Services Service Sid Streams Sid
    post:
      description: Update a specific Stream.
      tags:
        - Services
        - Streams
      summary: Create Services Service Sid Streams Sid
  /v1/Services/{ServiceSid}/Streams:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Stream.
      tags:
        - Services
        - Streams
      summary: Create Services Service Sid Streams
    get:
      description: Retrieve a list of all Streams in a Service Instance.
      tags:
        - Services
        - Streams
      summary: Retrieve Services Service Sid Streams
tags:
  - name: SyncV1Document
  - name: SyncV1DocumentPermission
  - name: SyncV1Service
  - name: SyncV1StreamMessage
  - name: SyncV1SyncList
  - name: SyncV1SyncListItem
  - name: SyncV1SyncListPermission
  - name: SyncV1SyncMap
  - name: SyncV1SyncMapItem
  - name: SyncV1SyncMapPermission
  - name: SyncV1SyncStream
x-maturity:
  - name: GA
    description: This product is G
