info:
  title: Twilio - Taskrouter
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Workspaces/{WorkspaceSid}/Activities/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Activities
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Activities Sid
    post:
      description: ''
      tags:
        - Activities
        - Workspaces
      summary: Create Workspaces Workspace Sid Activities Sid
    delete:
      description: ''
      tags:
        - Activities
        - Workspaces
      summary: Delete Workspaces Workspace Sid Activities Sid
  /v1/Workspaces/{WorkspaceSid}/Activities:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Activities
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Activities
    post:
      description: ''
      tags:
        - Activities
        - Workspaces
      summary: Create Workspaces Workspace Sid Activities
  /v1/Workspaces/{WorkspaceSid}/Events/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Events
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Events Sid
  /v1/Workspaces/{WorkspaceSid}/Events:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Events
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Events
  /v1/Workspaces/{WorkspaceSid}/Tasks/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Tasks Sid
    post:
      description: ''
      tags:
        - Tasks
        - Workspaces
      summary: Create Workspaces Workspace Sid Tasks Sid
    delete:
      description: ''
      tags:
        - Tasks
        - Workspaces
      summary: Delete Workspaces Workspace Sid Tasks Sid
  /v1/Workspaces/{WorkspaceSid}/Tasks:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Tasks
    post:
      description: ''
      tags:
        - Tasks
        - Workspaces
      summary: Create Workspaces Workspace Sid Tasks
  /v1/Workspaces/{WorkspaceSid}/TaskChannels/{Sid}:
    description: Types of tasks
    get:
      description: ''
      tags:
        - Channels
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Task Channels Sid
    post:
      description: ''
      tags:
        - Channels
        - Tasks
        - Workspaces
      summary: Create Workspaces Workspace Sid Task Channels Sid
    delete:
      description: ''
      tags:
        - Channels
        - Tasks
        - Workspaces
      summary: Delete Workspaces Workspace Sid Task Channels Sid
  /v1/Workspaces/{WorkspaceSid}/TaskChannels:
    description: Types of tasks
    get:
      description: ''
      tags:
        - Channels
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Task Channels
    post:
      description: ''
      tags:
        - Channels
        - Tasks
        - Workspaces
      summary: Create Workspaces Workspace Sid Task Channels
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Queues
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Task Queues Sid
    post:
      description: ''
      tags:
        - Queues
        - Tasks
        - Workspaces
      summary: Create Workspaces Workspace Sid Task Queues Sid
    delete:
      description: ''
      tags:
        - Queues
        - Tasks
        - Workspaces
      summary: Delete Workspaces Workspace Sid Task Queues Sid
  /v1/Workspaces/{WorkspaceSid}/TaskQueues:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Queues
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Task Queues
    post:
      description: ''
      tags:
        - Queues
        - Tasks
        - Workspaces
      summary: Create Workspaces Workspace Sid Task Queues
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/CumulativeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Cumulative
        - Queues
        - Statistics
        - Tasks
        - Workspaces
      summary: >-
        Retrieve Workspaces Workspace Sid Task Queues Task Queue Sid Cumulative
        Statistics
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Queues
        - Statistics
        - Tasks
        - Time
        - Workspaces
      summary: >-
        Retrieve Workspaces Workspace Sid Task Queues Task Queue Sid Real Time
        Statistics
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/{TaskQueueSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Queues
        - Statistics
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Task Queues Task Queue Sid Statistics
  /v1/Workspaces/{WorkspaceSid}/TaskQueues/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Queues
        - Statistics
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Task Queues Statistics
  /v1/Workspaces/{WorkspaceSid}/Tasks/{TaskSid}/Reservations:
    description: Tasks reserved for workers
    get:
      description: ''
      tags:
        - Reservations
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Tasks Task Sid Reservations
  /v1/Workspaces/{WorkspaceSid}/Tasks/{TaskSid}/Reservations/{Sid}:
    description: Tasks reserved for workers
    get:
      description: ''
      tags:
        - Reservations
        - Tasks
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Tasks Task Sid Reservations Sid
    post:
      description: ''
      tags:
        - Reservations
        - Tasks
        - Workspaces
      summary: Create Workspaces Workspace Sid Tasks Task Sid Reservations Sid
  /v1/Workspaces/{WorkspaceSid}/Workers:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers
    post:
      description: ''
      tags:
        - Workers
        - Workspaces
      summary: Create Workspaces Workspace Sid Workers
  /v1/Workspaces/{WorkspaceSid}/Workers/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Sid
    post:
      description: ''
      tags:
        - Workers
        - Workspaces
      summary: Create Workspaces Workspace Sid Workers Sid
    delete:
      description: ''
      tags:
        - Workers
        - Workspaces
      summary: Delete Workspaces Workspace Sid Workers Sid
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Channels:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Channels
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Worker Sid Channels
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Channels/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Channels
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Worker Sid Channels Sid
    post:
      description: ''
      tags:
        - Channels
        - Workers
        - Workspaces
      summary: Create Workspaces Workspace Sid Workers Worker Sid Channels Sid
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Statistics
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Worker Sid Statistics
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Reservations:
    description: Current and past reservations for a worker
    get:
      description: ''
      tags:
        - Reservations
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Worker Sid Reservations
  /v1/Workspaces/{WorkspaceSid}/Workers/{WorkerSid}/Reservations/{Sid}:
    description: Current and past reservations for a worker
    get:
      description: ''
      tags:
        - Reservations
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Worker Sid Reservations Sid
    post:
      description: ''
      tags:
        - Reservations
        - Workers
        - Workspaces
      summary: Create Workspaces Workspace Sid Workers Worker Sid Reservations Sid
  /v1/Workspaces/{WorkspaceSid}/Workers/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Statistics
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Statistics
  /v1/Workspaces/{WorkspaceSid}/Workers/CumulativeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Cumulative
        - Statistics
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Cumulative Statistics
  /v1/Workspaces/{WorkspaceSid}/Workers/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Statistics
        - Time
        - Workers
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workers Real Time Statistics
  /v1/Workspaces/{WorkspaceSid}/Workflows/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Workflows
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workflows Sid
    post:
      description: ''
      tags:
        - Workflows
        - Workspaces
      summary: Create Workspaces Workspace Sid Workflows Sid
    delete:
      description: ''
      tags:
        - Workflows
        - Workspaces
      summary: Delete Workspaces Workspace Sid Workflows Sid
  /v1/Workspaces/{WorkspaceSid}/Workflows:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Workflows
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workflows
    post:
      description: ''
      tags:
        - Workflows
        - Workspaces
      summary: Create Workspaces Workspace Sid Workflows
  /v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/CumulativeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Cumulative
        - Statistics
        - Workflows
        - Workspaces
      summary: >-
        Retrieve Workspaces Workspace Sid Workflows Workflow Sid Cumulative
        Statistics
  /v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Statistics
        - Time
        - Workflows
        - Workspaces
      summary: >-
        Retrieve Workspaces Workspace Sid Workflows Workflow Sid Real Time
        Statistics
  /v1/Workspaces/{WorkspaceSid}/Workflows/{WorkflowSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Statistics
        - Workflows
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Workflows Workflow Sid Statistics
  /v1/Workspaces/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Workspaces
      summary: Retrieve Workspaces Sid
    post:
      description: ''
      tags:
        - Workspaces
      summary: Create Workspaces Sid
    delete:
      description: ''
      tags:
        - Workspaces
      summary: Delete Workspaces Sid
  /v1/Workspaces:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Workspaces
      summary: Retrieve Workspaces
    post:
      description: ''
      tags:
        - Workspaces
      summary: Create Workspaces
  /v1/Workspaces/{WorkspaceSid}/CumulativeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Cumulative
        - Statistics
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Cumulative Statistics
  /v1/Workspaces/{WorkspaceSid}/RealTimeStatistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Statistics
        - Time
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Real Time Statistics
  /v1/Workspaces/{WorkspaceSid}/Statistics:
    description: 'TODO: Resource-level docs'
    get:
      description: ''
      tags:
        - Statistics
        - Workspaces
      summary: Retrieve Workspaces Workspace Sid Statistics
tags:
  - name: TaskrouterV1Activity
  - name: TaskrouterV1Event
  - name: TaskrouterV1Reservation
  - name: TaskrouterV1Task
  - name: TaskrouterV1TaskChannel
  - name: TaskrouterV1TaskQueue
  - name: TaskrouterV1TaskQueueCumulativeStatistics
  - name: TaskrouterV1TaskQueueRealTimeStatistics
  - name: TaskrouterV1TaskQueueStatistics
  - name: TaskrouterV1TaskQueuesStatistics
  - name: TaskrouterV1Worker
  - name: TaskrouterV1WorkerChannel
  - name: TaskrouterV1WorkerStatistics
  - name: TaskrouterV1WorkersCumulativeStatistics
  - name: TaskrouterV1WorkersRealTimeStatistics
  - name: TaskrouterV1WorkersStatistics
  - name: TaskrouterV1Workflow
  - name: TaskrouterV1WorkflowCumulativeStatistics
  - name: TaskrouterV1WorkflowRealTimeStatistics
  - name: TaskrouterV1WorkflowStatistics
  - name: TaskrouterV1Workspace
  - name: TaskrouterV1WorkspaceCumulativeStatistics
  - name: TaskrouterV1WorkspaceRealTimeStatistics
  - name: TaskrouterV1WorkspaceStatistics
x-maturity:
  - name: GA
    description: This product is G
