info:
  title: Twilio - Trunking
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/Trunks/{TrunkSid}/CredentialLists/{Sid}:
    description: List of credentials for accessing a trunk
    get:
      description: ''
      tags:
        - Credentials
        - Trunks
      summary: Retrieve Trunks Trunk Sid Credential Lists Sid
    delete:
      description: ''
      tags:
        - Credentials
        - Trunks
      summary: Delete Trunks Trunk Sid Credential Lists Sid
  /v1/Trunks/{TrunkSid}/CredentialLists:
    description: List of credentials for accessing a trunk
    post:
      description: ''
      tags:
        - Credentials
        - Trunks
      summary: Create Trunks Trunk Sid Credential Lists
    get:
      description: ''
      tags:
        - Credentials
        - Trunks
      summary: Retrieve Trunks Trunk Sid Credential Lists
  /v1/Trunks/{TrunkSid}/IpAccessControlLists/{Sid}:
    description: List of IP addresses for accessing a trunk
    get:
      description: ''
      tags:
        - Access
        - Controls
        - IP
        - Trunks
      summary: Retrieve Trunks Trunk Sid Ip Access Control Lists Sid
    delete:
      description: Remove an associated IP Access Control List from a Trunk
      tags:
        - Access
        - Controls
        - IP
        - Trunks
      summary: Delete Trunks Trunk Sid Ip Access Control Lists Sid
  /v1/Trunks/{TrunkSid}/IpAccessControlLists:
    description: List of IP addresses for accessing a trunk
    post:
      description: Associate an IP Access Control List with a Trunk
      tags:
        - Access
        - Controls
        - IP
        - Trunks
      summary: Create Trunks Trunk Sid Ip Access Control Lists
    get:
      description: List all IP Access Control Lists for a Trunk
      tags:
        - Access
        - Controls
        - IP
        - Trunks
      summary: Retrieve Trunks Trunk Sid Ip Access Control Lists
  /v1/Trunks/{TrunkSid}/OriginationUrls/{Sid}:
    description: Network element entry points into your communications infrastructure
    get:
      description: ''
      tags:
        - Origination
        - Trunks
        - URL
      summary: Retrieve Trunks Trunk Sid Origination Urls Sid
    delete:
      description: ''
      tags:
        - Origination
        - Trunks
        - URL
      summary: Delete Trunks Trunk Sid Origination Urls Sid
    post:
      description: ''
      tags:
        - Origination
        - Trunks
        - URL
      summary: Create Trunks Trunk Sid Origination Urls Sid
  /v1/Trunks/{TrunkSid}/OriginationUrls:
    description: Network element entry points into your communications infrastructure
    post:
      description: ''
      tags:
        - Origination
        - Trunks
        - URL
      summary: Create Trunks Trunk Sid Origination Urls
    get:
      description: ''
      tags:
        - Origination
        - Trunks
        - URL
      summary: Retrieve Trunks Trunk Sid Origination Urls
  /v1/Trunks/{TrunkSid}/PhoneNumbers/{Sid}:
    description: Phone numbers associated with trunks
    get:
      description: ''
      tags:
        - Numbers
        - Phone
        - Trunks
      summary: Retrieve Trunks Trunk Sid Phone Numbers Sid
    delete:
      description: ''
      tags:
        - Numbers
        - Phone
        - Trunks
      summary: Delete Trunks Trunk Sid Phone Numbers Sid
  /v1/Trunks/{TrunkSid}/PhoneNumbers:
    description: Phone numbers associated with trunks
    post:
      description: ''
      tags:
        - Numbers
        - Phone
        - Trunks
      summary: Create Trunks Trunk Sid Phone Numbers
    get:
      description: ''
      tags:
        - Numbers
        - Phone
        - Trunks
      summary: Retrieve Trunks Trunk Sid Phone Numbers
  /v1/Trunks/{TrunkSid}/Recording:
    description: Recording settings for a trunk
    get:
      description: ''
      tags:
        - Recording
        - Trunks
      summary: Retrieve Trunks Trunk Sid Recording
    post:
      description: ''
      tags:
        - Recording
        - Trunks
      summary: Create Trunks Trunk Sid Recording
  /v1/Trunks/{Sid}:
    description: Represents a SIP trunk
    get:
      description: ''
      tags:
        - Trunks
      summary: Retrieve Trunks Sid
    delete:
      description: ''
      tags:
        - Trunks
      summary: Delete Trunks Sid
    post:
      description: ''
      tags:
        - Trunks
      summary: Create Trunks Sid
  /v1/Trunks:
    description: Represents a SIP trunk
    post:
      description: ''
      tags:
        - Trunks
      summary: Create Trunks
    get:
      description: ''
      tags:
        - Trunks
      summary: Retrieve Trunks
tags:
  - name: TrunkingV1CredentialList
  - name: TrunkingV1IpAccessControlList
  - name: TrunkingV1OriginationUrl
  - name: TrunkingV1PhoneNumber
  - name: TrunkingV1Recording
  - name: TrunkingV1Trunk
x-maturity:
  - name: GA
    description: This product is G
