info:
  title: Twilio - Trusthub
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/ComplianceInquiries/Customers/Initialize:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Create a new Compliance Inquiry for the authenticated account. This is
        necessary to start a new embedded session.
      tags:
        - Compliance
        - Customers
        - Initialize
        - Inquiries
      summary: Create Compliance Inquiries Customers Initialize
  /v1/ComplianceInquiries/Customers/{CustomerId}/Initialize:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Resume a specific Compliance Inquiry that has expired, or re-open a
        rejected Compliance Inquiry for editing.
      tags:
        - Compliance
        - Customers
        - Initialize
        - Inquiries
      summary: Create Compliance Inquiries Customers Customer Id Initialize
  /v1/ComplianceInquiries/Tollfree/Initialize:
    description: 'TODO: Resource-level docs'
    post:
      description: >-
        Create a new Compliance Tollfree Verification Inquiry for the
        authenticated account. This is necessary to start a new embedded
        session.
      tags:
        - Compliance
        - Initialize
        - Inquiries
        - Toll Free
      summary: Create Compliance Inquiries Tollfree Initialize
  /v1/CustomerProfiles:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Customer-Profile.
      tags:
        - Customers
        - Profiles
      summary: Create Customer Profiles
    get:
      description: Retrieve a list of all Customer-Profiles for an account.
      tags:
        - Customers
        - Profiles
      summary: Retrieve Customer Profiles
  /v1/CustomerProfiles/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Customer-Profile instance.
      tags:
        - Customers
        - Profiles
      summary: Retrieve Customer Profiles Sid
    post:
      description: Updates a Customer-Profile in an account.
      tags:
        - Customers
        - Profiles
      summary: Create Customer Profiles Sid
    delete:
      description: Delete a specific Customer-Profile.
      tags:
        - Customers
        - Profiles
      summary: Delete Customer Profiles Sid
  /v1/CustomerProfiles/{CustomerProfileSid}/ChannelEndpointAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - Assignments
        - Channels
        - Customers
        - Endpoints
        - Profiles
      summary: >-
        Create Customer Profiles Customer Profile Sid Channel Endpoint
        Assignments
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - Assignments
        - Channels
        - Customers
        - Endpoints
        - Profiles
      summary: >-
        Retrieve Customer Profiles Customer Profile Sid Channel Endpoint
        Assignments
  /v1/CustomerProfiles/{CustomerProfileSid}/ChannelEndpointAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - Assignments
        - Channels
        - Customers
        - Endpoints
        - Profiles
      summary: >-
        Retrieve Customer Profiles Customer Profile Sid Channel Endpoint
        Assignments Sid
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - Assignments
        - Channels
        - Customers
        - Endpoints
        - Profiles
      summary: >-
        Delete Customer Profiles Customer Profile Sid Channel Endpoint
        Assignments Sid
  /v1/CustomerProfiles/{CustomerProfileSid}/EntityAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - Assignments
        - Customers
        - Entities
        - Profiles
      summary: Create Customer Profiles Customer Profile Sid Entity Assignments
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - Assignments
        - Customers
        - Entities
        - Profiles
      summary: Retrieve Customer Profiles Customer Profile Sid Entity Assignments
  /v1/CustomerProfiles/{CustomerProfileSid}/EntityAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - Assignments
        - Customers
        - Entities
        - Profiles
      summary: Retrieve Customer Profiles Customer Profile Sid Entity Assignments Sid
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - Assignments
        - Customers
        - Entities
        - Profiles
      summary: Delete Customer Profiles Customer Profile Sid Entity Assignments Sid
  /v1/CustomerProfiles/{CustomerProfileSid}/Evaluations:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Evaluation
      tags:
        - Customers
        - Evaluations
        - Profiles
      summary: Create Customer Profiles Customer Profile Sid Evaluations
    get:
      description: >-
        Retrieve a list of Evaluations associated to the customer_profile
        resource.
      tags:
        - Customers
        - Evaluations
        - Profiles
      summary: Retrieve Customer Profiles Customer Profile Sid Evaluations
  /v1/CustomerProfiles/{CustomerProfileSid}/Evaluations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Evaluation Instance.
      tags:
        - Customers
        - Evaluations
        - Profiles
      summary: Retrieve Customer Profiles Customer Profile Sid Evaluations Sid
  /v1/EndUsers:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new End User.
      tags:
        - Users
      summary: Create End Users
    get:
      description: Retrieve a list of all End User for an account.
      tags:
        - Users
      summary: Retrieve End Users
  /v1/EndUsers/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific End User Instance.
      tags:
        - Users
      summary: Retrieve End Users Sid
    post:
      description: Update an existing End User.
      tags:
        - Users
      summary: Create End Users Sid
    delete:
      description: Delete a specific End User.
      tags:
        - Users
      summary: Delete End Users Sid
  /v1/EndUserTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all End-User Types.
      tags:
        - Types
        - Users
      summary: Retrieve End User Types
  /v1/EndUserTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific End-User Type Instance.
      tags:
        - Types
        - Users
      summary: Retrieve End User Types Sid
  /v1/Policies:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Policys.
      tags:
        - Policies
      summary: Retrieve Policies
  /v1/Policies/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Policy Instance.
      tags:
        - Policies
      summary: Retrieve Policies Sid
  /v1/SupportingDocuments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Supporting Document.
      tags:
        - Documents
        - Supporting
      summary: Create Supporting Documents
    get:
      description: Retrieve a list of all Supporting Document for an account.
      tags:
        - Documents
        - Supporting
      summary: Retrieve Supporting Documents
  /v1/SupportingDocuments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Supporting Document Instance.
      tags:
        - Documents
        - Supporting
      summary: Retrieve Supporting Documents Sid
    post:
      description: Update an existing Supporting Document.
      tags:
        - Documents
        - Supporting
      summary: Create Supporting Documents Sid
    delete:
      description: Delete a specific Supporting Document.
      tags:
        - Documents
        - Supporting
      summary: Delete Supporting Documents Sid
  /v1/SupportingDocumentTypes:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Supporting Document Types.
      tags:
        - Documents
        - Supporting
        - Types
      summary: Retrieve Supporting Document Types
  /v1/SupportingDocumentTypes/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Supporting Document Type Instance.
      tags:
        - Documents
        - Supporting
        - Types
      summary: Retrieve Supporting Document Types Sid
  /v1/TrustProducts:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Customer-Profile.
      tags:
        - Products
        - Trust
      summary: Create Trust Products
    get:
      description: Retrieve a list of all Customer-Profiles for an account.
      tags:
        - Products
        - Trust
      summary: Retrieve Trust Products
  /v1/TrustProducts/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Customer-Profile instance.
      tags:
        - Products
        - Trust
      summary: Retrieve Trust Products Sid
    post:
      description: Updates a Customer-Profile in an account.
      tags:
        - Products
        - Trust
      summary: Create Trust Products Sid
    delete:
      description: Delete a specific Customer-Profile.
      tags:
        - Products
        - Trust
      summary: Delete Trust Products Sid
  /v1/TrustProducts/{TrustProductSid}/ChannelEndpointAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - Assignments
        - Channels
        - Endpoints
        - Products
        - Trust
      summary: Create Trust Products Trust Product Sid Channel Endpoint Assignments
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - Assignments
        - Channels
        - Endpoints
        - Products
        - Trust
      summary: Retrieve Trust Products Trust Product Sid Channel Endpoint Assignments
  /v1/TrustProducts/{TrustProductSid}/ChannelEndpointAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - Assignments
        - Channels
        - Endpoints
        - Products
        - Trust
      summary: >-
        Retrieve Trust Products Trust Product Sid Channel Endpoint Assignments
        Sid
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - Assignments
        - Channels
        - Endpoints
        - Products
        - Trust
      summary: Delete Trust Products Trust Product Sid Channel Endpoint Assignments Sid
  /v1/TrustProducts/{TrustProductSid}/EntityAssignments:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Assigned Item.
      tags:
        - Assignments
        - Entities
        - Products
        - Trust
      summary: Create Trust Products Trust Product Sid Entity Assignments
    get:
      description: Retrieve a list of all Assigned Items for an account.
      tags:
        - Assignments
        - Entities
        - Products
        - Trust
      summary: Retrieve Trust Products Trust Product Sid Entity Assignments
  /v1/TrustProducts/{TrustProductSid}/EntityAssignments/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Assigned Item Instance.
      tags:
        - Assignments
        - Entities
        - Products
        - Trust
      summary: Retrieve Trust Products Trust Product Sid Entity Assignments Sid
    delete:
      description: Remove an Assignment Item Instance.
      tags:
        - Assignments
        - Entities
        - Products
        - Trust
      summary: Delete Trust Products Trust Product Sid Entity Assignments Sid
  /v1/TrustProducts/{TrustProductSid}/Evaluations:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Evaluation
      tags:
        - Evaluations
        - Products
        - Trust
      summary: Create Trust Products Trust Product Sid Evaluations
    get:
      description: Retrieve a list of Evaluations associated to the trust_product resource.
      tags:
        - Evaluations
        - Products
        - Trust
      summary: Retrieve Trust Products Trust Product Sid Evaluations
  /v1/TrustProducts/{TrustProductSid}/Evaluations/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Evaluation Instance.
      tags:
        - Evaluations
        - Products
        - Trust
      summary: Retrieve Trust Products Trust Product Sid Evaluations Sid
tags:
  - name: TrusthubV1ComplianceInquiries
  - name: TrusthubV1ComplianceTollfreeInquiries
  - name: TrusthubV1CustomerProfiles
  - name: TrusthubV1CustomerProfilesChannelEndpointAssignment
  - name: TrusthubV1CustomerProfilesEntityAssignments
  - name: TrusthubV1CustomerProfilesEvaluations
  - name: TrusthubV1EndUser
  - name: TrusthubV1EndUserType
  - name: TrusthubV1Policies
  - name: TrusthubV1SupportingDocument
  - name: TrusthubV1SupportingDocumentType
  - name: TrusthubV1TrustProducts
  - name: TrusthubV1TrustProductsChannelEndpointAssignment
  - name: TrusthubV1TrustProductsEntityAssignments
  - name: TrusthubV1TrustProductsEvaluations
x-maturity:
  - name: GA
    description: This product is G
