info:
  title: Twilio - Verify
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v2/Services/{ServiceSid}/AccessTokens:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new enrollment Access Token for the Entity
      tags:
        - Access
        - Services
        - Tokens
      summary: Create Services Service Sid Access Tokens
  /v2/Services/{ServiceSid}/AccessTokens/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch an Access Token for the Entity
      tags:
        - Access
        - Services
        - Tokens
      summary: Retrieve Services Service Sid Access Tokens Sid
  /v2/Services/{ServiceSid}/RateLimits/{RateLimitSid}/Buckets:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Bucket for a Rate Limit
      tags:
        - Buckets
        - Limits
        - Rates
        - Services
      summary: Create Services Service Sid Rate Limits Rate Limit Sid Buckets
    get:
      description: Retrieve a list of all Buckets for a Rate Limit.
      tags:
        - Buckets
        - Limits
        - Rates
        - Services
      summary: Retrieve Services Service Sid Rate Limits Rate Limit Sid Buckets
  /v2/Services/{ServiceSid}/RateLimits/{RateLimitSid}/Buckets/{Sid}:
    description: 'TODO: Resource-level docs'
    post:
      description: Update a specific Bucket.
      tags:
        - Buckets
        - Limits
        - Rates
        - Services
      summary: Create Services Service Sid Rate Limits Rate Limit Sid Buckets Sid
    get:
      description: Fetch a specific Bucket.
      tags:
        - Buckets
        - Limits
        - Rates
        - Services
      summary: Retrieve Services Service Sid Rate Limits Rate Limit Sid Buckets Sid
    delete:
      description: Delete a specific Bucket.
      tags:
        - Buckets
        - Limits
        - Rates
        - Services
      summary: Delete Services Service Sid Rate Limits Rate Limit Sid Buckets Sid
  /v2/Services/{ServiceSid}/Entities/{Identity}/Challenges:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Challenge for the Factor
      tags:
        - Challenges
        - Entities
        - Identity
        - Services
      summary: Create Services Service Sid Entities Identity Challenges
    get:
      description: Retrieve a list of all Challenges for a Factor.
      tags:
        - Challenges
        - Entities
        - Identity
        - Services
      summary: Retrieve Services Service Sid Entities Identity Challenges
  /v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific Challenge.
      tags:
        - Challenges
        - Entities
        - Identity
        - Services
      summary: Retrieve Services Service Sid Entities Identity Challenges Sid
    post:
      description: Verify a specific Challenge.
      tags:
        - Challenges
        - Entities
        - Identity
        - Services
      summary: Create Services Service Sid Entities Identity Challenges Sid
  /v2/Services/{ServiceSid}/Entities:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Entity for the Service
      tags:
        - Entities
        - Services
      summary: Create Services Service Sid Entities
    get:
      description: Retrieve a list of all Entities for a Service.
      tags:
        - Entities
        - Services
      summary: Retrieve Services Service Sid Entities
  /v2/Services/{ServiceSid}/Entities/{Identity}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Entity.
      tags:
        - Entities
        - Identity
        - Services
      summary: Delete Services Service Sid Entities Identity
    get:
      description: Fetch a specific Entity.
      tags:
        - Entities
        - Identity
        - Services
      summary: Retrieve Services Service Sid Entities Identity
  /v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}:
    description: 'TODO: Resource-level docs'
    delete:
      description: Delete a specific Factor.
      tags:
        - Entities
        - Factors
        - Identity
        - Services
      summary: Delete Services Service Sid Entities Identity Factors Sid
    get:
      description: Fetch a specific Factor.
      tags:
        - Entities
        - Factors
        - Identity
        - Services
      summary: Retrieve Services Service Sid Entities Identity Factors Sid
    post:
      description: >-
        Update a specific Factor. This endpoint can be used to Verify a Factor
        if passed an `AuthPayload` param.
      tags:
        - Entities
        - Factors
        - Identity
        - Services
      summary: Create Services Service Sid Entities Identity Factors Sid
  /v2/Services/{ServiceSid}/Entities/{Identity}/Factors:
    description: 'TODO: Resource-level docs'
    get:
      description: Retrieve a list of all Factors for an Entity.
      tags:
        - Entities
        - Factors
        - Identity
        - Services
      summary: Retrieve Services Service Sid Entities Identity Factors
    post:
      description: Create a new Factor for the Entity
      tags:
        - Entities
        - Factors
        - Identity
        - Services
      summary: Create Services Service Sid Entities Identity Factors
  /v2/Forms/{FormType}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch the forms for a specific Form Type.
      tags:
        - Forms
        - Types
      summary: Retrieve Forms Form Type
  /v2/Services/{ServiceSid}/MessagingConfigurations:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new MessagingConfiguration for a service.
      tags:
        - Configurations
        - Messaging
        - Services
      summary: Create Services Service Sid Messaging Configurations
    get:
      description: Retrieve a list of all Messaging Configurations for a Service.
      tags:
        - Configurations
        - Messaging
        - Services
      summary: Retrieve Services Service Sid Messaging Configurations
  /v2/Services/{ServiceSid}/MessagingConfigurations/{Country}:
    description: 'TODO: Resource-level docs'
    post:
      description: Update a specific MessagingConfiguration
      tags:
        - Configurations
        - Countries
        - Messaging
        - Services
      summary: Create Services Service Sid Messaging Configurations Country
    get:
      description: Fetch a specific MessagingConfiguration.
      tags:
        - Configurations
        - Countries
        - Messaging
        - Services
      summary: Retrieve Services Service Sid Messaging Configurations Country
    delete:
      description: Delete a specific MessagingConfiguration.
      tags:
        - Configurations
        - Countries
        - Messaging
        - Services
      summary: Delete Services Service Sid Messaging Configurations Country
  /v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{ChallengeSid}/Notifications:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Notification for the corresponding Challenge
      tags:
        - Challenges
        - Entities
        - Identity
        - Notifications
        - Services
      summary: >-
        Create Services Service Sid Entities Identity Challenges Challenge Sid
        Notifications
  /v2/Services/{ServiceSid}/RateLimits:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Rate Limit for a Service
      tags:
        - Limits
        - Rates
        - Services
      summary: Create Services Service Sid Rate Limits
    get:
      description: Retrieve a list of all Rate Limits for a service.
      tags:
        - Limits
        - Rates
        - Services
      summary: Retrieve Services Service Sid Rate Limits
  /v2/Services/{ServiceSid}/RateLimits/{Sid}:
    description: 'TODO: Resource-level docs'
    post:
      description: Update a specific Rate Limit.
      tags:
        - Limits
        - Rates
        - Services
      summary: Create Services Service Sid Rate Limits Sid
    get:
      description: Fetch a specific Rate Limit.
      tags:
        - Limits
        - Rates
        - Services
      summary: Retrieve Services Service Sid Rate Limits Sid
    delete:
      description: Delete a specific Rate Limit.
      tags:
        - Limits
        - Rates
        - Services
      summary: Delete Services Service Sid Rate Limits Sid
  /v2/SafeList/Numbers:
    description: 'TODO: Resource-level docs'
    post:
      description: Add a new phone number to SafeList.
      tags:
        - Numbers
        - Safe
      summary: Create Safe List Numbers
  /v2/SafeList/Numbers/{PhoneNumber}:
    description: 'TODO: Resource-level docs'
    get:
      description: Check if a phone number exists in SafeList.
      tags:
        - Numbers
        - Phone
        - Safe
      summary: Retrieve Safe List Numbers Phone Number
    delete:
      description: Remove a phone number from SafeList.
      tags:
        - Numbers
        - Phone
        - Safe
      summary: Delete Safe List Numbers Phone Number
  /v2/Services:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Verification Service.
      tags:
        - Services
      summary: Create Services
    get:
      description: Retrieve a list of all Verification Services for an account.
      tags:
        - Services
      summary: Retrieve Services
  /v2/Services/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch specific Verification Service Instance.
      tags:
        - Services
      summary: Retrieve Services Sid
    delete:
      description: Delete a specific Verification Service Instance.
      tags:
        - Services
      summary: Delete Services Sid
    post:
      description: Update a specific Verification Service.
      tags:
        - Services
      summary: Create Services Sid
  /v2/Services/{ServiceSid}/Verifications:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Verification using a Service
      tags:
        - Services
        - Verifications
      summary: Create Services Service Sid Verifications
  /v2/Services/{ServiceSid}/Verifications/{Sid}:
    description: 'TODO: Resource-level docs'
    post:
      description: Update a Verification status
      tags:
        - Services
        - Verifications
      summary: Create Services Service Sid Verifications Sid
    get:
      description: Fetch a specific Verification
      tags:
        - Services
        - Verifications
      summary: Retrieve Services Service Sid Verifications Sid
  /v2/Attempts:
    description: 'TODO: Resource-level docs'
    get:
      description: List all the verification attempts for a given Account.
      tags:
        - Attempts
      summary: Retrieve Attempts
  /v2/Attempts/{Sid}:
    description: 'TODO: Resource-level docs'
    get:
      description: Fetch a specific verification attempt.
      tags:
        - Attempts
      summary: Retrieve Attempts Sid
  /v2/Attempts/Summary:
    description: 'TODO: Resource-level docs'
    get:
      description: >-
        Get a summary of how many attempts were made and how many were
        converted.
      tags:
        - Attempts
        - Summaries
      summary: Retrieve Attempts Summary
  /v2/Services/{ServiceSid}/VerificationCheck:
    description: 'TODO: Resource-level docs'
    post:
      description: challenge a specific Verification Check.
      tags:
        - Checks
        - Services
        - Verification
      summary: Create Services Service Sid Verification Check
  /v2/Templates:
    description: 'TODO: Resource-level docs'
    get:
      description: List all the available templates for a given Account.
      tags:
        - Templates
      summary: Retrieve Templates
  /v2/Services/{ServiceSid}/Webhooks:
    description: 'TODO: Resource-level docs'
    post:
      description: Create a new Webhook for the Service
      tags:
        - Services
        - Webhooks
      summary: Create Services Service Sid Webhooks
    get:
      description: Retrieve a list of all Webhooks for a Service.
      tags:
        - Services
        - Webhooks
      summary: Retrieve Services Service Sid Webhooks
  /v2/Services/{ServiceSid}/Webhooks/{Sid}:
    description: 'TODO: Resource-level docs'
    post:
      description: ''
      tags:
        - Services
        - Webhooks
      summary: Create Services Service Sid Webhooks Sid
    delete:
      description: Delete a specific Webhook.
      tags:
        - Services
        - Webhooks
      summary: Delete Services Service Sid Webhooks Sid
    get:
      description: Fetch a specific Webhook.
      tags:
        - Services
        - Webhooks
      summary: Retrieve Services Service Sid Webhooks Sid
tags:
  - name: VerifyV2AccessToken
  - name: VerifyV2Bucket
  - name: VerifyV2Challenge
  - name: VerifyV2Entity
  - name: VerifyV2Factor
  - name: VerifyV2Form
  - name: VerifyV2MessagingConfiguration
  - name: VerifyV2NewFactor
  - name: VerifyV2Notification
  - name: VerifyV2RateLimit
  - name: VerifyV2Safelist
  - name: VerifyV2Service
  - name: VerifyV2Template
  - name: VerifyV2Verification
  - name: VerifyV2VerificationAttempt
  - name: VerifyV2VerificationAttemptsSummary
  - name: VerifyV2VerificationCheck
  - name: VerifyV2Webhook
x-maturity:
  - name: GA
    description: This product is Generally Available.
  - name: Beta
    description: PLEASE NOTE that this is a Beta product that is subject to change. U
