info:
  title: Twilio - Wireless
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
openapi: 3.0.1
paths:
  /v1/UsageRecords:
    description: Aggregated Usage information for all SIMs on an Account
    get:
      description: ''
      tags:
        - Records
        - Usage
      summary: Retrieve Usage Records
  /v1/Commands/{Sid}:
    description: Machine-to-machine commands sent to/from devices
    get:
      description: Fetch a Command instance from your account.
      tags:
        - Commands
      summary: Retrieve Commands Sid
    delete:
      description: Delete a Command instance from your account.
      tags:
        - Commands
      summary: Delete Commands Sid
  /v1/Commands:
    description: Machine-to-machine commands sent to/from devices
    get:
      description: Retrieve a list of Commands from your account.
      tags:
        - Commands
      summary: Retrieve Commands
    post:
      description: Send a Command to a Sim.
      tags:
        - Commands
      summary: Create Commands
  /v1/Sims/{SimSid}/DataSessions:
    description: Data session information for SIMs
    get:
      description: ''
      tags:
        - Data
        - SIMs
        - Sessions
      summary: Retrieve Sims Sim Sid Data Sessions
  /v1/RatePlans:
    description: Capabilities and restrictions for SIMs
    get:
      description: ''
      tags:
        - Plans
        - Rates
      summary: Retrieve Rate Plans
    post:
      description: ''
      tags:
        - Plans
        - Rates
      summary: Create Rate Plans
  /v1/RatePlans/{Sid}:
    description: Capabilities and restrictions for SIMs
    get:
      description: ''
      tags:
        - Plans
        - Rates
      summary: Retrieve Rate Plans Sid
    post:
      description: ''
      tags:
        - Plans
        - Rates
      summary: Create Rate Plans Sid
    delete:
      description: ''
      tags:
        - Plans
        - Rates
      summary: Delete Rate Plans Sid
  /v1/Sims/{Sid}:
    description: A resource representing a Programmable Wireless SIM
    get:
      description: Fetch a Sim resource on your Account.
      tags:
        - SIMs
      summary: Retrieve Sims Sid
    post:
      description: Updates the given properties of a Sim resource on your Account.
      tags:
        - SIMs
      summary: Create Sims Sid
    delete:
      description: Delete a Sim resource on your Account.
      tags:
        - SIMs
      summary: Delete Sims Sid
  /v1/Sims:
    description: A resource representing a Programmable Wireless SIM
    get:
      description: Retrieve a list of Sim resources on your Account.
      tags:
        - SIMs
      summary: Retrieve Sims
  /v1/Sims/{SimSid}/UsageRecords:
    description: Usage information for SIMs
    get:
      description: ''
      tags:
        - Records
        - SIMs
        - Usage
      summary: Retrieve Sims Sim Sid Usage Records
tags:
  - name: WirelessV1Command
  - name: WirelessV1DataSession
  - name: WirelessV1RatePlan
  - name: WirelessV1Sim
  - name: WirelessV1UsageRecord
x-maturity:
  - name: GA
    description: This product is G
